### ISSUE TITLE
Extension does not work in Code - Insiders

### ISSUE THREAD

**Issue by jsbravoc** [tylim88/VS-Code-Folder-HIde#1]
https://github.com/tylim88/VS-Code-Folder-HIde/blob/445038af8a3821a82e258bd8b56757d8574dce4b/src/extension.ts#L45

The location of the the Code - Insiders config file is `.config/Code - Insiders/User/settings.json`

**Comment by tylim88** [comment]
please try version 0.2.0 or above

**Comment by tylim88** [comment]
I assumed it is working, please let me know if it is not
